# Generated by Django 5.0.6 on 2024-06-28 18:30

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0003_alter_cvinformation_id_alter_cvlanguage_id_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cvinformation',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_informations', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='cvprojectlanguage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cv_project_languages', to='users.cvproject'),
        ),
        migrations.AlterField(
            model_name='githubprojectlanguage',
            name='project',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='github_project_languages', to='users.githubproject'),
        ),
        migrations.AlterUniqueTogether(
            name='cvinformation',
            unique_together={('user', 'headline')},
        ),
        migrations.AlterUniqueTogether(
            name='cvlanguage',
            unique_together={('user', 'language')},
        ),
        migrations.AlterUniqueTogether(
            name='cvprojectlanguage',
            unique_together={('language', 'project')},
        ),
        migrations.AlterUniqueTogether(
            name='githubprojectlanguage',
            unique_together={('language', 'project')},
        ),
    ]
