# Generated by Django 5.0.6 on 2024-07-15 20:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0006_remove_cvlanguage_proficiency'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='cvskill',
            unique_together={('user', 'skill')},
        ),
    ]
