# Generated by Django 5.0.6 on 2024-07-18 10:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0008_alter_cvcertification_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='cvcertification',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cveducation',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvexperience',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvlanguage',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvproject',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='cvskill',
            name='is_manual_added',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_background',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='myuser',
            name='profile_photo',
            field=models.URLField(blank=True, null=True),
        ),
    ]
